### PR TITLE
Remove tests to accommodate rb-m-t-cassandra-ng changes

### PR DESCRIPTION
**Pull request by eevans**
This is to support the changes related to the storage module redesign (aka restbase-mod-table-cassandra-ng).  It will need to be installed alongside the current one, so it has an alternative name (for now).

Bug: https://phabricator.wikimedia.org/T169938

### CODE REVIEW

**Comment by Pchelolo** [comment]
Do you wanna separate `revisionRetentionPolicy` tests in a separate PR?

**Comment by eevans** [comment]
> Do you wanna separate revisionRetentionPolicy tests in a separate PR?

Yeah, good point; This is all still very WIP, what I needed for the [wikimedia/restbase-mod-table-cassandra](https://github.com/wikimedia/restbase-mod-table-cassandra) work so far.  I honestly hadn't thought about it (I guess they'd move to [wikimedia/restbase](https://github.com/wikimedia/restbase)?).

**Comment by Pchelolo** [comment]
Not quire sure where would they go, but since we still have a normal branch I think we can just boldly delete all of them

**Comment by Pchelolo** [comment]
Also, there's some code related to secondary indexes in `lib/validator.js`

**Comment by Pchelolo** [comment]
+1!

**Comment by d00rman** [comment]
The _secondary index must be defined_ test is failing and should probably not even be there

**Pull request merged**
