### PR TITLE
Remove ttl doc

### PR DESCRIPTION
**Pull request by gwicke**

### CODE REVIEW

**Comment by gwicke** [comment]
cc @wikimedia/services 

This is dependent on the validation patch, as those two patches otherwise end up clashing. I can reorder the patches if you'd prefer to merge the README first.

**Comment by Pchelolo** [comment]
The TTL removal part looks good to me

**Comment by gwicke** [comment]
I have gone ahead & published this as v0.1.3, so that dependent tests can pass.

**Comment by d00rman** [comment]
@gwicke please tag the release

**Pull request merged**
