### PR TITLE
Release v0.0.8

### PR DESCRIPTION
**Pull request by d00rman**

### CODE REVIEW

**Comment by d00rman** [comment]
cc @Pchelolo

**Comment by Pchelolo** [comment]
LGTM. Weird, how did it happen that 0.0.7 already exist, I though I've based a branch on a current master..

**Comment by d00rman** [comment]
@Pchelolo could be that you based your PR on your fork's master, not wikimedia's

**Comment by d00rman** [comment]
Published as v0.0.8

**Comment by Pchelolo** [comment]
@d00rman must have forgotten to do a `pull upstream`.. 

Now after this is merged we need to focus on [a cassandra update](https://github.com/wikimedia/restbase-mod-table-cassandra/pull/154) because the tests are gonna fail as soon as 0.0.8 spec is published.

**Pull request merged**
