### PR TITLE
Merge the 'redesign' branch into master

### PR DESCRIPTION
**Pull request by eevans**
Merges branch `redesign` into master as version 1.0.0, bringing full circle the storage strategy refactor.

### CODE REVIEW

**Comment by d00rman** [comment]
I guess these merge conflicts need to be resolved. Also, could you make the PR from the redesign branch onto master rather than your master? We can keep the history that way.

**Comment by eevans** [comment]
> I guess these merge conflicts need to be resolved.

Merge conflicts?

> Also, could you make the PR from the redesign branch onto master rather than your master? We can keep the history that way.

I can do that (I will do that), but I'm curious as to why; Isn't the history identical either way?

**Comment by eevans** [comment]
Closing in favor of https://github.com/wikimedia/restbase-mod-table-spec/pull/49

**Comment by d00rman** [comment]
> I can do that (I will do that), but I'm curious as to why; Isn't the history identical either way?

I meant history in the sense it coming from the redesign branch :)

**Pull request closed without merging**
